export type IconType =
  | 'acrobatic'
  | 'blade-drag'
  | 'bolt-spell-cast'
  | 'convince'
  | 'crossed-swords'
  | 'divert'
  | 'egyptian-walk'
  | 'extra-time'
  | 'goblin'
  | 'high-shot'
  | 'invisible'
  | 'magnifying-glass'
  | 'person'
  | 'player-time'
  | 'pull'
  | 'shield-bash'
  | 'spell-book'
  | 'surprised'
  | 'swordwoman'
  | 'sword-clash'
  | 'talk'
  | 'walk'
;